
- name: install system dependencies
  sudo: yes
  apt: pkg={{item}} state=latest
  with_items:
    - libgmp10
    - nginx

- name: write nginx.conf
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: configure hazard upstart job
  sudo: yes
  template: src=hazard.upstart.j2 dest=/etc/init/hazard.conf

- name: create app-server user
  sudo: yes
  user:
    state: present
    name: "{{ app_server_user }}"
    system: yes

- name: obtain the latest app-server binary
  sudo: yes
  sudo_user: "{{ app_server_user }}"
  fetch_url:
    dest: "/home/{{ app_server_user }}/hazard"
    mode: 0544
    # XXX: Make this a parameter
    url: http://hydra.mumak.net/job/loveletter/hazard/build/latest/download/1/hazard/bin/hazard
    # XXX: Not ideal to have to edit this every time we want to deploy.
    sha256sum: dd9f07e1fab0813c4da43347ea7e65edc470c54e5b169dd0635d33a4de9e34e3
  notify:
    - restart app-server

- name: upload certificate
  sudo: yes
  copy:
    src: "{{ local_ssl_certificate_path }}"
    dest: "{{ ssl_certificate_path }}"

- name: upload intermediate certificates
  sudo: yes
  copy:
    src: "{{ local_ssl_ca_path }}"
    dest: "{{ ssl_ca_path }}"

- name: bundle intermediate certificates with site certificate
  sudo: yes
  shell: "cat {{ ssl_ca_path }} >> {{ ssl_certificate_path }}"

- name: bundle intermediate certificates with root certificate
  sudo: yes
  shell: "cat {{ ssl_ca_path }} {{ ssl_root_certificate_path }} > {{ ssl_ca_bundle_path }}"

- name: upload key
  sudo: yes
  copy:
    src: "{{ local_ssl_key_path }}"
    dest: "{{ ssl_key_path }}"
